### ISSUE TITLE
Multiple util modules used for unused uniq function?

### ISSUE THREAD

**Issue by Grinnz** [biosails/BioSAILs#1]
List::Uniq and List::MoreUtils both are used in this distribution to import a 'uniq' function but it does not seem to be used currently. FYI List::Util 1.45 now implements 'uniq' so the other two are not needed for this anymore; in addition, List::MoreUtils has a convoluted packaging and licensing situation so it is recommended to use List::Util or List::SomeUtils instead.

**Comment by jerowe** [comment]
Thanks - will update ASAP.
